create table if not exists groups (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists schedule (
  id bigint generated by default as identity primary key,
  group_id bigint not null references groups(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 1 and 6),
  lesson_number smallint not null,
  subject_name text not null,
  time_start time not null,
  time_end time not null
);

alter table groups enable row level security;
alter table schedule enable row level security;

drop policy if exists "Public read groups" on groups;
create policy "Public read groups" on groups
for select to anon, authenticated using (true);

drop policy if exists "Public read schedule" on schedule;
create policy "Public read schedule" on schedule
for select to anon, authenticated using (true);
